name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Diesel
      run: cargo install diesel_cli --no-default-features --features sqlite
    - name: Prepare Test DB
      run: diesel migration run --database-url test-backend.sqlite
    - name: Build
      run: cargo build

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup fmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --check